# Google Takeout folder structure

# Takeout/
# ├── +1/
# ├── Google+ stream/
# |   ├── Posts/
# |   ├── Photos/
# |   |   ├── Photos of posts/
# |   |   └── Photos of polls/
# |   ├── Activities/
# |   ├── Collections/
# |   └── Events/
# └── index.html

gto:
    # "G+ stream" folder
    stream: Stream in Google+
    # "Posts" folder
    posts: Beiträge

site:
    lang: de
    descr:
    url: http://localhost:8000/
    email:
    title: Static G+ stream archive

shared:
    public: "Geteilt mit: Öffentlich"
    circles: "Geteilt mit: Meine Kreise"
    extcircles: "Geteilt mit: Meine erweiterten Kreise"
    com: "Shared to the community"
    coll: "Shared to the collection"
    event: "Shared to the event"
    # none of the above
    other: "Andere"

import:
    # include posts that are none of the first three options (public,
    # circles, extcircles), shared to certain circles or persons/profiles
    # so these are probably private posts
    # (considered as "Andere"/"Other")
    private: True
    # exclude circles from import
    circle_filter:
        - circle1
        - circle2
    # include posts to communities (may be closed/private)
    com: True
    # exclude communities from import
    com_filter:
        - com1
        - com2
    # include posts to events (may be not public)
    event: True

