# Google Takeout folder structure

# Takeout/
# ├── +1/
# ├── Google+ stream/
# |   ├── Posts/
# |   ├── Photos/
# |   |   ├── Photos of posts/
# |   |   └── Photos of polls/
# |   ├── Activities/
# |   ├── Collections/
# |   └── Events/
# └── index.html

gto:
    # "G+ stream" folder
    stream: Stream in Google+
    # "Posts" folder
    posts: Beiträge

site:
    lang: de
    descr:
    url: http://localhost:8000/
    email:
    title: Static G+ stream archive
    # main website/blog
    main_url:

shared:
    # shared public
    public: "Geteilt mit: Öffentlich"
    # shared to "my circles"
    circles: "Geteilt mit: Meine Kreise"
    # shared to "my extended circles"
    extcircles: "Geteilt mit: Meine erweiterten Kreise"
    # shared to community
    com: "Shared to the community"
    # shared to collection
    coll: "Shared to the collection"
    # shared to event
    event: "Shared to the event"
    # none of the above, this will not affect the import
    # name of category with "other" posts
    other: "Andere"

import:
    # include posts that are none of the first three options (public,
    # circles, extcircles), shared to certain circles or persons/profiles
    # so these are probably private posts
    # (considered as "Andere"/"Other")
    private: True
    # exclude circles from import (may be empty)
    circle_filter:
        - circle1
        - circle2
    # include posts to communities (may be closed/private)
    com: True
    # exclude communities from import (may be empty)
    com_filter:
        - com1
        - com2
    # include posts to events (may be not public)
    event: True

image:
    watermark: False
    watermark_text: Don't copy that floppy!

